# Generated by Django 3.2 on 2026-05-09 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100, verbose_name='店铺名称')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='merchants/logos/', verbose_name='店铺Logo')),
                ('description', models.TextField(blank=True, verbose_name='店铺简介')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='联系邮箱')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='店铺地址')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='审核状态')),
                ('reject_reason', models.TextField(blank=True, verbose_name='拒绝原因')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='总销售额')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='总订单数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '商家',
                'verbose_name_plural': '商家',
                'ordering': ['-created_at'],
            },
        ),
    ]
