# Generated by Django 3.2 on 2026-05-14 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_add_payment_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0, verbose_name='积分余额')),
                ('total_earned', models.PositiveIntegerField(default=0, verbose_name='累计获得')),
                ('total_used', models.PositiveIntegerField(default=0, verbose_name='累计使用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='points_account', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '积分账户',
                'verbose_name_plural': '积分账户',
            },
        ),
        migrations.CreateModel(
            name='PointsExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='兑换商品名称')),
                ('image', models.ImageField(blank=True, null=True, upload_to='points_exchange/', verbose_name='图片')),
                ('points_required', models.PositiveIntegerField(verbose_name='所需积分')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='库存')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '积分兑换商品',
                'verbose_name_plural': '积分兑换商品',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(verbose_name='积分变动（正数获得，负数使用）')),
                ('balance_after', models.PositiveIntegerField(verbose_name='变动后余额')),
                ('record_type', models.CharField(choices=[('purchase', '购物获得'), ('checkin', '签到获得'), ('bonus', '奖励获得'), ('exchange', '积分兑换'), ('expire', '积分过期'), ('admin', '管理员调整')], max_length=20, verbose_name='类型')),
                ('description', models.CharField(max_length=200, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='points.pointsaccount', verbose_name='账户')),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order', verbose_name='关联订单')),
            ],
            options={
                'verbose_name': '积分记录',
                'verbose_name_plural': '积分记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointsExchangeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_used', models.PositiveIntegerField(verbose_name='使用积分')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('shipped', '已发货'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='收货地址')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exchange_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='points.pointsexchange', verbose_name='兑换商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_orders', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '积分兑换订单',
                'verbose_name_plural': '积分兑换订单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckInRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateField(verbose_name='签到日期')),
                ('continuous_days', models.PositiveIntegerField(default=1, verbose_name='连续签到天数')),
                ('points_earned', models.PositiveIntegerField(verbose_name='获得积分')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '签到记录',
                'verbose_name_plural': '签到记录',
                'ordering': ['-checkin_date'],
                'unique_together': {('user', 'checkin_date')},
            },
        ),
    ]
