# Generated by Django 3.2 on 2026-05-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='日期')),
                ('order_count', models.PositiveIntegerField(default=0, verbose_name='订单数')),
                ('order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='订单金额')),
                ('new_users', models.PositiveIntegerField(default=0, verbose_name='新增用户')),
                ('active_users', models.PositiveIntegerField(default=0, verbose_name='活跃用户')),
                ('product_views', models.PositiveIntegerField(default=0, verbose_name='商品浏览量')),
                ('paid_orders', models.PositiveIntegerField(default=0, verbose_name='支付订单数')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='支付金额')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '每日统计',
                'verbose_name_plural': '每日统计',
                'ordering': ['-date'],
            },
        ),
    ]
