"""
Django settings for lu_django project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ounm1ubj46u3m9&v5($&5r@6y&x$+b*p!lo-)@uq#5&j#t4v6&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
    'goods',
    'cart',
    'users',
    'orders',
    'merchant',
    'points',
    'analytics',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lu_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.cart_total',
                'main.context_processors.categories',
            ],
        },
    },
]

WSGI_APPLICATION = 'lu_django.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'lu_db',
        'USER': 'root',      # 替换为你的MySQL用户名
        'PASSWORD': '434200lc.',  # 替换为密码
        'HOST': 'localhost',
        'PORT': '3306',
    }
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

# 媒体文件（用户上传的商品图片等）
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 登录后重定向到个人中心
LOGIN_REDIRECT_URL = 'users:profile'
# 登录 URL
LOGIN_URL = 'login'
# 登出后重定向到首页
LOGOUT_REDIRECT_URL = 'main:index'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.qq.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'XXXXXXXXX@XX.com'
EMAIL_HOST_PASSWORD = 'fkohniexfidedbec'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

SIMPLEUI_HOME_INFO = False  # 关闭首页的广告和服务器信息
SIMPLEUI_ANALYSIS = False   # 关闭使用统计
SIMPLEUI_HEADER = True      # 显示顶部栏
SIMPLEUI_LOGO = 'https://www.djangoproject.com/m/img/site/hdr_logo.png' # 可以换成你的 logo 地址
SIMPLEUI_DEFAULT_THEME = 'admin.lte.css' # 设置默认主题

# 积分配置
POINTS_CONFIG = {
    'PURCHASE_RATE': 1,  # 每消费1元获得1积分
    'CHECKIN_BASE': 10,  # 签到基础积分
    'CHECKIN_BONUS': {   # 连续签到奖励
        7: 20,
        14: 30,
        30: 50,
    },
}
