# Generated by Django 5.2.6 on 2026-04-30 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_remove_product_review_count_review'),
        ('main', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.product', verbose_name='关联商品'),
        ),
        migrations.AlterField(
            model_name='carouselimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='carousel/'),
        ),
    ]
