# Generated by Django 5.2.6 on 2026-04-30 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_remove_product_review_count_review'),
        ('main', '0004_carouselimage_product_alter_carouselimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimage',
            name='link',
            field=models.CharField(blank=True, help_text='自定义链接，如果关联商品则可留空', max_length=200),
        ),
        migrations.AlterField(
            model_name='carouselimage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carousel_images', to='goods.product'),
        ),
    ]
