# Generated by Django 3.2 on 2026-05-09 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
        ('goods', '0003_remove_product_review_count_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='merchant.merchant', verbose_name='商家'),
        ),
        migrations.AddField(
            model_name='product',
            name='reject_reason',
            field=models.TextField(blank=True, verbose_name='拒绝原因'),
        ),
        migrations.AddField(
            model_name='product',
            name='review_status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='approved', max_length=20, verbose_name='审核状态'),
        ),
        migrations.AddField(
            model_name='product',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
    ]
